// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductionContext.Infrastructure.Persistence;

#nullable disable

namespace ProductionContext.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProductionDbContext))]
    [Migration("20260912173339_InitialProduction")]
    partial class InitialProduction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("ProductionContext.Domain.Entities.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<double?>("FinalDurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<long?>("FinalFileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FinalVideoPath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("MontageSettings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug");

                    b.HasIndex("Status");

                    b.ToTable("production_projects", (string)null);
                });

            modelBuilder.Entity("ProductionContext.Domain.Entities.Scene", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("EndSeconds")
                        .HasColumnType("REAL");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RenderedVideoAssetId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SceneCodeId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SceneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double>("StartSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisualNote")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Index");

                    b.HasIndex("ProjectId", "SceneId")
                        .IsUnique();

                    b.ToTable("production_scenes", (string)null);
                });

            modelBuilder.Entity("ProductionContext.Domain.Entities.SceneFragment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BrollAssetId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DeclaredEndSeconds")
                        .HasColumnType("REAL");

                    b.Property<double>("DeclaredStartSeconds")
                        .HasColumnType("REAL");

                    b.Property<double>("EndSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("FragmentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAnimationMissing")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMediaMissing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SceneEntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double>("StartSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisualNote")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("VoiceAssetId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Index");

                    b.HasIndex("SceneEntityId");

                    b.ToTable("production_scene_fragments", (string)null);
                });

            modelBuilder.Entity("ProductionContext.Domain.Entities.Scene", b =>
                {
                    b.HasOne("ProductionContext.Domain.Entities.Project", null)
                        .WithMany("Scenes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductionContext.Domain.Entities.SceneFragment", b =>
                {
                    b.HasOne("ProductionContext.Domain.Entities.Scene", null)
                        .WithMany("Fragments")
                        .HasForeignKey("SceneEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductionContext.Domain.Entities.Project", b =>
                {
                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("ProductionContext.Domain.Entities.Scene", b =>
                {
                    b.Navigation("Fragments");
                });
#pragma warning restore 612, 618
        }
    }
}
