namespace Integrations.YouTube.Innertube.Contracts;

public enum InnerTubeClientType
{
    Web,
    Android,
    Tv,
    Ios
}

public sealed record InnerTubeVideoItem(
    string VideoId,
    string Title,
    string ChannelTitle,
    string ChannelId,
    long ViewCount,
    int DurationSeconds,
    bool IsShort,
    string PublishedText,
    string Url,
    string ThumbnailUrl,
    long SubscriberCount = 0,
    bool IsVerified = false,
    string Description = "");

public sealed record InnerTubeSubtitleTrack(
    string LanguageCode,
    string Name,
    string BaseUrl,
    bool IsAutoGenerated);

public sealed record InnerTubeComment(
    string AuthorName,
    string AuthorChannelId,
    string Text,
    int LikeCount,
    string PublishedTime,
    string CommentId,
    string? ContinuationToken = null,
    string Category = "general");

public sealed record InnerTubeHeatmapPoint(
    double StartSeconds,
    double EndSeconds,
    double Intensity);

public sealed record InnerTubeVideoChapter(
    int StartSeconds,
    int EndSeconds,
    string Title,
    string ThumbnailUrl);

public sealed record InnerTubeWordTimestamp(
    double StartMs,
    double EndMs,
    string Word);

public sealed record InnerTubeChannelUpload(
    string VideoId,
    string Title,
    string ThumbnailUrl,
    int ViewCount,
    string PublishedText,
    int DurationSeconds);

public sealed record InnerTubeChannelStats(
    long SubscriberCount,
    long TotalViewCount,
    int VideoCount,
    string Description);

public sealed class InnerTubeSearchFilter
{
    public string? Type { get; set; }
    public string? Duration { get; set; }
    public string? SortBy { get; set; }
    public string? UploadDate { get; set; }
    public string? Features { get; set; }
    public string? License { get; set; }
}
