namespace Integrations.YouTube.Innertube.Contracts;

public enum InnerTubeClientType
{
    Web,
    Android,
    Tv
}

public sealed record InnerTubeVideoItem(
    string VideoId,
    string Title,
    string ChannelTitle,
    string ChannelId,
    long ViewCount,
    int DurationSeconds,
    bool IsShort,
    string PublishedText,
    string Url,
    string ThumbnailUrl,
    long SubscriberCount = 0,
    bool IsVerified = false,
    string Description = "");

public sealed record InnerTubeSubtitleTrack(
    string LanguageCode,
    string Name,
    string BaseUrl,
    bool IsAutoGenerated);

public sealed record InnerTubeComment(
    string AuthorName,
    string AuthorChannelId,
    string Text,
    int LikeCount,
    string PublishedTime,
    string CommentId);
