// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using SystemContext.Infrastructure.Persistence;

#nullable disable

namespace SystemContext.Infrastructure.Persistence.Migrations;

[DbContext(typeof(SystemDbContext))]
partial class SystemDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

        modelBuilder.Entity("SystemContext.Domain.Entities.AiModelArtifact", b =>
        {
            b.Property<string>("Id").HasMaxLength(64).HasColumnType("TEXT");
            b.Property<string>("Category").IsRequired().HasMaxLength(32).HasColumnType("TEXT");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("TEXT");
            b.Property<string>("DownloadUrl").IsRequired().HasMaxLength(1024).HasColumnType("TEXT");
            b.Property<long>("DownloadedSizeBytes").HasColumnType("INTEGER");
            b.Property<string>("ErrorMessage").HasMaxLength(1024).HasColumnType("TEXT");
            b.Property<long>("ExpectedSizeBytes").HasColumnType("INTEGER");
            b.Property<bool>("IsRequired").HasColumnType("INTEGER");
            b.Property<string>("Name").IsRequired().HasMaxLength(128).HasColumnType("TEXT");
            b.Property<string>("Sha256Checksum").HasMaxLength(128).HasColumnType("TEXT");
            b.Property<string>("Status").IsRequired().HasMaxLength(32).HasColumnType("TEXT");
            b.Property<string>("TargetDirectory").IsRequired().HasMaxLength(256).HasColumnType("TEXT");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("TEXT");
            b.Property<string>("Version").IsRequired().HasMaxLength(32).HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("Category");
            b.HasIndex("Status");
            b.ToTable("ai_models", (string)null);
        });

        modelBuilder.Entity("SystemContext.Domain.Entities.SystemMaintenanceLog", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("TEXT");
            b.Property<long>("DurationMs").HasColumnType("INTEGER");
            b.Property<bool>("IsSuccess").HasColumnType("INTEGER");
            b.Property<string>("Operation").IsRequired().HasMaxLength(128).HasColumnType("TEXT");
            b.Property<string>("Details").HasColumnType("TEXT");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("CreatedAt");
            b.ToTable("system_maintenance_logs", (string)null);
        });

        modelBuilder.Entity("SystemContext.Domain.Entities.SystemSetting", b =>
        {
            b.Property<string>("Id").HasMaxLength(128).HasColumnType("TEXT");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("TEXT");
            b.Property<string>("DataType").IsRequired().HasMaxLength(32).HasColumnType("TEXT");
            b.Property<string>("Description").IsRequired().HasMaxLength(512).HasColumnType("TEXT");
            b.Property<bool>("IsReadOnly").HasColumnType("INTEGER");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("TEXT");
            b.Property<string>("Value").IsRequired().HasMaxLength(4096).HasColumnType("TEXT");
            b.HasKey("Id");
            b.ToTable("system_settings", (string)null);
        });
#pragma warning restore 612, 618
    }
}
