// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Research.Infrastructure.Persistence;

#nullable disable

namespace Research.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ResearchDbContext))]
    [Migration("20260912173411_InitialResearch")]
    partial class InitialResearch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Research.Domain.Entities.EarlySignal", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double>("AggregateVph")
                        .HasColumnType("REAL");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrowthPct")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<double>("GrowthVelocityPercent")
                        .HasColumnType("REAL");

                    b.Property<string>("KeywordClusterJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResearchRunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePlatform")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<int>("SupportingVideoCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResearchRunId");

                    b.ToTable("research_early_signals", (string)null);
                });

            modelBuilder.Entity("Research.Domain.Entities.Opportunity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AngleTitle")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FrictionPoint")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("HookHypothesis")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecommendedFormat")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceVideoIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResearchRunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetAudience")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WhyItWorks")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("Score", "Research.Domain.Entities.Opportunity.Score#OpportunityScore", b1 =>
                        {
                            b1.Property<double>("CompetitionIndex")
                                .HasColumnType("REAL")
                                .HasColumnName("competition_index");

                            b1.Property<double>("DemandVelocity")
                                .HasColumnType("REAL")
                                .HasColumnName("demand_velocity");

                            b1.Property<double>("Value")
                                .HasColumnType("REAL")
                                .HasColumnName("opportunity_score");

                            b1.Property<double>("ViralConfidence")
                                .HasColumnType("REAL")
                                .HasColumnName("viral_confidence");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ResearchRunId");

                    b.ToTable("research_opportunities", (string)null);
                });

            modelBuilder.Entity("Research.Domain.Entities.ResearchRun", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Niche")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TopicQuery")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("research_runs", (string)null);
                });

            modelBuilder.Entity("Research.Domain.Entities.VideoCandidate", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("ChannelSubscriberCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChannelTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResearchRunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("TopCommentsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty<Dictionary<string, object>>("Momentum", "Research.Domain.Entities.VideoCandidate.Momentum#MomentumScore", b1 =>
                        {
                            b1.Property<double>("OutlierMultiplier")
                                .HasColumnType("REAL")
                                .HasColumnName("outlier_multiplier");

                            b1.Property<double>("Score")
                                .HasColumnType("REAL")
                                .HasColumnName("momentum_score");

                            b1.Property<double>("ViewsPerHour")
                                .HasColumnType("REAL")
                                .HasColumnName("views_per_hour");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ResearchRunId");

                    b.HasIndex("VideoId");

                    b.ToTable("research_video_candidates", (string)null);
                });

            modelBuilder.Entity("Research.Domain.Entities.EarlySignal", b =>
                {
                    b.HasOne("Research.Domain.Entities.ResearchRun", null)
                        .WithMany("Signals")
                        .HasForeignKey("ResearchRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Research.Domain.Entities.Opportunity", b =>
                {
                    b.HasOne("Research.Domain.Entities.ResearchRun", null)
                        .WithMany("Opportunities")
                        .HasForeignKey("ResearchRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Research.Domain.Entities.VideoCandidate", b =>
                {
                    b.HasOne("Research.Domain.Entities.ResearchRun", null)
                        .WithMany("Candidates")
                        .HasForeignKey("ResearchRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Research.Domain.Entities.ResearchRun", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("Opportunities");

                    b.Navigation("Signals");
                });
#pragma warning restore 612, 618
        }
    }
}
