// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Skills.Infrastructure.Persistence;

#nullable disable

namespace Skills.Infrastructure.Persistence.Migrations;

[DbContext(typeof(SkillsDbContext))]
[Migration("20260903000001_InitialSkills")]
partial class InitialSkills
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

        modelBuilder.Entity("Skills.Domain.Entities.Skill", b =>
        {
            b.Property<string>("Id")
                .HasMaxLength(64)
                .HasColumnType("TEXT");

            b.Property<string>("Content")
                .IsRequired()
                .HasMaxLength(32000)
                .HasColumnType("TEXT");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("TEXT");

            b.Property<string>("DefaultContent")
                .HasMaxLength(32000)
                .HasColumnType("TEXT");

            b.Property<string>("Description")
                .IsRequired()
                .HasMaxLength(512)
                .HasColumnType("TEXT");

            b.Property<bool>("IsDefault")
                .HasColumnType("INTEGER");

            b.Property<bool>("IsEnabled")
                .HasColumnType("INTEGER");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("TEXT");

            b.Property<int>("Priority")
                .HasColumnType("INTEGER");

            b.Property<string>("Stage")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("TEXT");

            b.Property<string>("Tags")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<DateTimeOffset>("UpdatedAt")
                .HasColumnType("TEXT");

            b.Property<int>("Version")
                .HasColumnType("INTEGER");

            b.HasKey("Id");

            b.HasIndex("IsEnabled");

            b.HasIndex("Priority");

            b.HasIndex("Stage");

            b.ToTable("skills", (string)null);
        });
#pragma warning restore 612, 618
    }
}
