using System.Text;
using System.Text.Json;
using Integrations.YouTube.Innertube.Contracts;
using Integrations.YouTube.Innertube.Extractors;

namespace Integrations.YouTube.Innertube.Extractors;

public interface IPlayerResponseExtractor
{
    IReadOnlyList<InnerTubeVideoItem> ExtractVideoItems(JsonElement root, int maxResults = 25);
    IReadOnlyList<InnerTubeSubtitleTrack> ExtractSubtitleTracks(JsonElement root);
    string? ExtractVideoId(JsonElement root);
    string? ExtractTitle(JsonElement root);
    long ExtractViewCount(JsonElement root);
    int ExtractDurationSeconds(JsonElement root);
}

public sealed class PlayerResponseExtractor : IPlayerResponseExtractor
{
    private readonly Config.InnerTubeSchemaConfig _schema;

    public PlayerResponseExtractor(Config.InnerTubeSchemaConfig schema)
    {
        _schema = schema;
    }

    public IReadOnlyList<InnerTubeVideoItem> ExtractVideoItems(JsonElement root, int maxResults = 25)
    {
        var results = new List<InnerTubeVideoItem>();
        if (root.ValueKind != JsonValueKind.Object) return results;

        if (root.TryGetProperty(_schema.VideoDetailsKey, out var videoDetails))
        {
            var item = ParseVideoDetails(videoDetails);
            if (item != null) results.Add(item);
        }

        return results.Take(maxResults).ToList();
    }

    public IReadOnlyList<InnerTubeSubtitleTrack> ExtractSubtitleTracks(JsonElement root)
    {
        var tracks = new List<InnerTubeSubtitleTrack>();

        if (!root.TryGetProperty(_schema.CaptionsKey, out var captions)) return tracks;
        if (!captions.TryGetProperty(_schema.PlayerCaptionsTracklistRendererKey, out var tracklist)) return tracks;
        if (!tracklist.TryGetProperty(_schema.CaptionTracksKey, out var tracksArray) ||
            tracksArray.ValueKind != JsonValueKind.Array) return tracks;

        foreach (var track in tracksArray.EnumerateArray())
        {
            var langCode = track.TryGetProperty("languageCode", out var lc) ? lc.GetString() ?? "" : "";
            var name = track.TryGetProperty("name", out var nameEl) ? nameEl.ExtractRunsText("simpleText") : langCode;
            var baseUrl = track.TryGetProperty("baseUrl", out var bu) ? bu.GetString() ?? "" : "";
            var isAuto = track.TryGetProperty("kind", out var kind) && kind.GetString() == "asr";

            if (!string.IsNullOrEmpty(baseUrl))
            {
                tracks.Add(new InnerTubeSubtitleTrack(
                    LanguageCode: langCode,
                    Name: name,
                    BaseUrl: baseUrl,
                    IsAutoGenerated: isAuto));
            }
        }

        return tracks;
    }

    public string? ExtractVideoId(JsonElement root)
    {
        if (root.TryGetProperty(_schema.VideoDetailsKey, out var vd) &&
            vd.TryGetProperty("videoId", out var vid))
        {
            return vid.GetString();
        }
        return null;
    }

    public string? ExtractTitle(JsonElement root)
    {
        if (root.TryGetProperty(_schema.VideoDetailsKey, out var vd))
            return vd.ExtractRunsText("title");
        return null;
    }

    public long ExtractViewCount(JsonElement root)
    {
        if (root.TryGetProperty(_schema.VideoDetailsKey, out var vd) &&
            vd.TryGetProperty("viewCount", out var vc) &&
            long.TryParse(vc.GetString(), out var count))
        {
            return count;
        }
        return 0;
    }

    public int ExtractDurationSeconds(JsonElement root)
    {
        if (root.TryGetProperty(_schema.VideoDetailsKey, out var vd) &&
            vd.TryGetProperty("lengthSeconds", out var ls) &&
            int.TryParse(ls.GetString(), out var seconds))
        {
            return seconds;
        }
        return 0;
    }

    private InnerTubeVideoItem? ParseVideoDetails(JsonElement vd)
    {
        if (!vd.TryGetProperty("videoId", out var vidProp)) return null;
        var vId = vidProp.GetString();
        if (string.IsNullOrEmpty(vId)) return null;

        var title = vd.ExtractRunsText("title");
        var channelTitle = vd.ExtractRunsText("author");
        var channelId = vd.TryGetProperty("channelId", out var cid) ? cid.GetString() ?? "" : "";
        var description = vd.TryGetProperty("shortDescription", out var sdp) ? sdp.GetString() ?? "" : "";
        var viewCount = ExtractViewCountFromElement(vd);
        var duration = ExtractDurationSecondsFromElement(vd);

        return new InnerTubeVideoItem(
            VideoId: vId,
            Title: title,
            ChannelTitle: channelTitle,
            ChannelId: channelId,
            ViewCount: viewCount,
            DurationSeconds: duration,
            IsShort: duration is > 0 and <= 180,
            PublishedText: "",
            Url: $"https://youtu.be/{vId}",
            ThumbnailUrl: $"https://i.ytimg.com/vi/{vId}/hqdefault.jpg",
            Description: description);
    }

    private static long ExtractViewCountFromElement(JsonElement root)
    {
        if (root.TryGetProperty("viewCount", out var vc) && vc.ValueKind == JsonValueKind.String)
            return long.TryParse(vc.GetString(), out var c) ? c : 0;
        if (root.TryGetProperty("viewCount", out var vn) && vn.ValueKind == JsonValueKind.Number)
            return vn.GetInt64();
        return 0;
    }

    private static int ExtractDurationSecondsFromElement(JsonElement root)
    {
        if (root.TryGetProperty("lengthSeconds", out var ls) && ls.ValueKind == JsonValueKind.String)
            return int.TryParse(ls.GetString(), out var s) ? s : 0;
        if (root.TryGetProperty("lengthSeconds", out var ln) && ln.ValueKind == JsonValueKind.Number)
            return ln.GetInt32();
        return 0;
    }
}
