using System.Text;
using System.Text.Json;
using Integrations.YouTube.Innertube.Contracts;
using Integrations.YouTube.Innertube.Extractors;

namespace Integrations.YouTube.Innertube.Extractors;

public interface IPlayerResponseExtractor
{
    IReadOnlyList<InnerTubeVideoItem> ExtractVideoItems(JsonElement root, int maxResults = 25);
    IReadOnlyList<InnerTubeSubtitleTrack> ExtractSubtitleTracks(JsonElement root);
    IReadOnlyList<InnerTubeHeatmapPoint> ExtractHeatmap(JsonElement root);
    IReadOnlyList<InnerTubeWordTimestamp> ExtractWordTimestamps(JsonElement root);
    string? ExtractVideoId(JsonElement root);
    string? ExtractTitle(JsonElement root);
    long ExtractViewCount(JsonElement root);
    int ExtractDurationSeconds(JsonElement root);
    string? FindNode(JsonElement root, string path);
}

public sealed class PlayerResponseExtractor : IPlayerResponseExtractor
{
    private readonly Config.InnerTubeSchemaConfig _schema;

    public PlayerResponseExtractor(Config.InnerTubeSchemaConfig schema)
    {
        _schema = schema;
    }

    public IReadOnlyList<InnerTubeVideoItem> ExtractVideoItems(JsonElement root, int maxResults = 25)
    {
        var results = new List<InnerTubeVideoItem>();
        if (root.ValueKind != JsonValueKind.Object) return results;

        if (root.TryGetProperty(_schema.VideoDetailsKey, out var videoDetails))
        {
            var item = ParseVideoDetails(videoDetails);
            if (item != null) results.Add(item);
        }

        return results.Take(maxResults).ToList();
    }

    public IReadOnlyList<InnerTubeSubtitleTrack> ExtractSubtitleTracks(JsonElement root)
    {
        var tracks = new List<InnerTubeSubtitleTrack>();

        if (!root.TryGetProperty(_schema.CaptionsKey, out var captions)) return tracks;
        if (!captions.TryGetProperty(_schema.PlayerCaptionsTracklistRendererKey, out var tracklist)) return tracks;
        if (!tracklist.TryGetProperty(_schema.CaptionTracksKey, out var tracksArray) ||
            tracksArray.ValueKind != JsonValueKind.Array) return tracks;

        foreach (var track in tracksArray.EnumerateArray())
        {
            var langCode = track.TryGetProperty("languageCode", out var lc) ? lc.GetString() ?? "" : "";
            var name = track.TryGetProperty("name", out var nameEl) ? nameEl.ExtractRunsText("simpleText") : langCode;
            var baseUrl = track.TryGetProperty("baseUrl", out var bu) ? bu.GetString() ?? "" : "";
            var isAuto = track.TryGetProperty("kind", out var kind) && kind.GetString() == "asr";

            if (!string.IsNullOrEmpty(baseUrl))
            {
                tracks.Add(new InnerTubeSubtitleTrack(
                    LanguageCode: langCode,
                    Name: name,
                    BaseUrl: baseUrl,
                    IsAutoGenerated: isAuto));
            }
        }

        return tracks;
    }

    public string? ExtractVideoId(JsonElement root)
    {
        if (root.TryGetProperty(_schema.VideoDetailsKey, out var vd) &&
            vd.TryGetProperty("videoId", out var vid))
        {
            return vid.GetString();
        }
        return null;
    }

    public string? ExtractTitle(JsonElement root)
    {
        if (root.TryGetProperty(_schema.VideoDetailsKey, out var vd))
            return vd.ExtractRunsText("title");
        return null;
    }

    public long ExtractViewCount(JsonElement root)
    {
        if (root.TryGetProperty(_schema.VideoDetailsKey, out var vd) &&
            vd.TryGetProperty("viewCount", out var vc) &&
            long.TryParse(vc.GetString(), out var count))
        {
            return count;
        }
        return 0;
    }

    public int ExtractDurationSeconds(JsonElement root)
    {
        if (root.TryGetProperty(_schema.VideoDetailsKey, out var vd) &&
            vd.TryGetProperty("lengthSeconds", out var ls) &&
            int.TryParse(ls.GetString(), out var seconds))
        {
            return seconds;
        }
        return 0;
    }

    public IReadOnlyList<InnerTubeHeatmapPoint> ExtractHeatmap(JsonElement root)
    {
        var points = new List<InnerTubeHeatmapPoint>();
        if (root.ValueKind != JsonValueKind.Object) return points;

        ExtractHeatmapFromFrameworkUpdates(root, points);
        if (points.Count > 0) return points;

        JsonElement renderer = default;

        if (root.TryGetProperty("playerHeatmapRenderer", out var hm))
        {
            renderer = hm;
        }
        else if (root.TryGetProperty(_schema.VideoDetailsKey, out var vd) &&
                 vd.TryGetProperty("playerHeatmapRenderer", out var vdHm))
        {
            renderer = vdHm;
        }

        if (renderer.ValueKind != JsonValueKind.Object) return points;

        if (!renderer.TryGetProperty("heatmap", out var heatmap) ||
            heatmap.ValueKind != JsonValueKind.Array)
            return points;

        foreach (var point in heatmap.EnumerateArray())
        {
            if (!point.TryGetProperty("startMillis", out var startEl) ||
                !point.TryGetProperty("endMillis", out var endEl) ||
                !point.TryGetProperty("intensity", out var intensityEl))
                continue;

            points.Add(new InnerTubeHeatmapPoint(
                ParseDouble(startEl) / 1000.0,
                ParseDouble(endEl) / 1000.0,
                ParseDouble(intensityEl)));
        }

        return points;
    }

    private static void ExtractHeatmapFromFrameworkUpdates(JsonElement root, List<InnerTubeHeatmapPoint> points)
    {
        if (!root.TryGetProperty("frameworkUpdates", out var frameworkUpdates) ||
            !frameworkUpdates.TryGetProperty("entityBatchUpdate", out var batchUpdate) ||
            !batchUpdate.TryGetProperty("mutations", out var mutations) ||
            mutations.ValueKind != JsonValueKind.Array)
            return;

        foreach (var mutation in mutations.EnumerateArray())
        {
            if (!mutation.TryGetProperty("payload", out var payload) ||
                !payload.TryGetProperty("macroMarkersListEntity", out var entity) ||
                !entity.TryGetProperty("markersList", out var markersList))
                continue;

            if (markersList.TryGetProperty("markerType", out var markerType) &&
                markerType.GetString() != "MARKER_TYPE_HEATMAP")
                continue;

            if (!markersList.TryGetProperty("markers", out var markers) ||
                markers.ValueKind != JsonValueKind.Array)
                continue;

            foreach (var marker in markers.EnumerateArray())
            {
                if (!marker.TryGetProperty("startMillis", out var startEl) ||
                    !marker.TryGetProperty("durationMillis", out var durationEl))
                    continue;

                var startMs = ParseDouble(startEl);
                var durationMs = ParseDouble(durationEl);
                var intensity = marker.TryGetProperty("intensityScoreNormalized", out var intensityEl)
                    ? ParseDouble(intensityEl)
                    : 0.0;

                points.Add(new InnerTubeHeatmapPoint(
                    startMs / 1000.0,
                    (startMs + durationMs) / 1000.0,
                    intensity));
            }
        }
    }

    private static double ParseDouble(JsonElement element)
    {
        return element.ValueKind switch
        {
            JsonValueKind.Number => element.GetDouble(),
            JsonValueKind.String => double.TryParse(
                element.GetString(), System.Globalization.NumberStyles.Float,
                System.Globalization.CultureInfo.InvariantCulture, out var value) ? value : 0.0,
            _ => 0.0
        };
    }

    public IReadOnlyList<InnerTubeWordTimestamp> ExtractWordTimestamps(JsonElement root)
    {
        var words = new List<InnerTubeWordTimestamp>();
        if (root.ValueKind != JsonValueKind.Object) return words;

        if (!root.TryGetProperty("videoDetails", out var vd)) return words;
        if (!vd.TryGetProperty("transcriptBodyRenderer", out var transcriptBody)) return words;
        if (!transcriptBody.TryGetProperty("cueGroups", out var cueGroups) ||
            cueGroups.ValueKind != JsonValueKind.Array)
            return words;

        foreach (var cueGroup in cueGroups.EnumerateArray())
        {
            if (!cueGroup.TryGetProperty("transcriptCueGroupRenderer", out var cgr)) continue;
            if (!cgr.TryGetProperty("cues", out var cues) || cues.ValueKind != JsonValueKind.Array) continue;

            foreach (var cue in cues.EnumerateArray())
            {
                if (!cue.TryGetProperty("transcriptCueRenderer", out var tcr)) continue;
                if (!tcr.TryGetProperty("startOffsetMs", out var startEl)) continue;
                if (!tcr.TryGetProperty("durationMs", out var durEl)) continue;
                if (!tcr.TryGetProperty("cue", out var cueContent)) continue;

                var text = cueContent.TryGetProperty("simpleText", out var st)
                    ? st.GetString() ?? ""
                    : cueContent.ExtractRunsText("runs");

                var startMs = double.TryParse(startEl.GetString(), System.Globalization.NumberStyles.Float,
                    System.Globalization.CultureInfo.InvariantCulture, out var s) ? s : 0;
                var durMs = double.TryParse(durEl.GetString(), System.Globalization.NumberStyles.Float,
                    System.Globalization.CultureInfo.InvariantCulture, out var d) ? d : 0;

                if (!string.IsNullOrWhiteSpace(text))
                    words.Add(new InnerTubeWordTimestamp(startMs, startMs + durMs, text.Trim()));
            }
        }

        return words;
    }

    public string? FindNode(JsonElement root, string path)
    {
        if (root.ValueKind != JsonValueKind.Object) return null;

        var parts = path.Split('.');
        var current = root;
        foreach (var part in parts)
        {
            if (!current.TryGetProperty(part, out var next)) return null;
            current = next;
        }

        return current.ValueKind switch
        {
            JsonValueKind.String => current.GetString(),
            JsonValueKind.Number => current.GetRawText(),
            JsonValueKind.True => "true",
            JsonValueKind.False => "false",
            _ => current.GetRawText()
        };
    }

    private InnerTubeVideoItem? ParseVideoDetails(JsonElement vd)
    {
        if (!vd.TryGetProperty("videoId", out var vidProp)) return null;
        var vId = vidProp.GetString();
        if (string.IsNullOrEmpty(vId)) return null;

        var title = vd.ExtractRunsText("title");
        var channelTitle = vd.ExtractRunsText("author");
        var channelId = vd.TryGetProperty("channelId", out var cid) ? cid.GetString() ?? "" : "";
        var description = vd.TryGetProperty("shortDescription", out var sdp) ? sdp.GetString() ?? "" : "";
        var viewCount = ExtractViewCountFromElement(vd);
        var duration = ExtractDurationSecondsFromElement(vd);

        return new InnerTubeVideoItem(
            VideoId: vId,
            Title: title,
            ChannelTitle: channelTitle,
            ChannelId: channelId,
            ViewCount: viewCount,
            DurationSeconds: duration,
            IsShort: duration is > 0 and <= 180,
            PublishedText: "",
            Url: $"https://youtu.be/{vId}",
            ThumbnailUrl: $"https://i.ytimg.com/vi/{vId}/hqdefault.jpg",
            Description: description);
    }

    private static long ExtractViewCountFromElement(JsonElement root)
    {
        if (root.TryGetProperty("viewCount", out var vc) && vc.ValueKind == JsonValueKind.String)
            return long.TryParse(vc.GetString(), out var c) ? c : 0;
        if (root.TryGetProperty("viewCount", out var vn) && vn.ValueKind == JsonValueKind.Number)
            return vn.GetInt64();
        return 0;
    }

    private static int ExtractDurationSecondsFromElement(JsonElement root)
    {
        if (root.TryGetProperty("lengthSeconds", out var ls) && ls.ValueKind == JsonValueKind.String)
            return int.TryParse(ls.GetString(), out var s) ? s : 0;
        if (root.TryGetProperty("lengthSeconds", out var ln) && ln.ValueKind == JsonValueKind.Number)
            return ln.GetInt32();
        return 0;
    }
}
