// <auto-generated />
using System;
using MediaContext.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace MediaContext.Infrastructure.Persistence.Migrations;

[DbContext(typeof(MediaDbContext))]
partial class MediaDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

        modelBuilder.Entity("MediaContext.Domain.Entities.MediaAsset", b =>
        {
            b.Property<string>("Id").HasMaxLength(64).HasColumnType("TEXT");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("TEXT");
            b.Property<string>("Dimensions").HasMaxLength(32).HasColumnType("TEXT");
            b.Property<double?>("Duration").HasColumnType("REAL");
            b.Property<string>("Extension").IsRequired().HasMaxLength(16).HasColumnType("TEXT");
            b.Property<long>("FileSizeBytes").HasColumnType("INTEGER");
            b.Property<double?>("Fps").HasColumnType("REAL");
            b.Property<bool>("IsNormalized").HasColumnType("INTEGER");
            b.Property<string>("NormalizedStoragePath").HasMaxLength(512).HasColumnType("TEXT");
            b.Property<string>("Sha256Hash").HasMaxLength(128).HasColumnType("TEXT");
            b.Property<string>("Source").IsRequired().HasMaxLength(32).HasColumnType("TEXT");
            b.Property<string>("StoragePath").IsRequired().HasMaxLength(512).HasColumnType("TEXT");
            b.Property<string>("Title").IsRequired().HasMaxLength(256).HasColumnType("TEXT");
            b.Property<string>("Type").IsRequired().HasMaxLength(32).HasColumnType("TEXT");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("IsNormalized");
            b.HasIndex("Source");
            b.HasIndex("Type");
            b.ToTable("media_assets", (string)null);
        });
#pragma warning restore 612, 618
    }
}
