// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotionContext.Infrastructure.Persistence;

#nullable disable

namespace MotionContext.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MotionDbContext))]
    partial class MotionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("MotionContext.Domain.Entities.SceneCode", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentRevisionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SceneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("Composition", "MotionContext.Domain.Entities.SceneCode.Composition#CompositionConfig", b1 =>
                        {
                            b1.Property<int>("DurationInFrames")
                                .HasColumnType("INTEGER")
                                .HasColumnName("duration_in_frames");

                            b1.Property<int>("Fps")
                                .HasColumnType("INTEGER")
                                .HasColumnName("fps");

                            b1.Property<int>("Height")
                                .HasColumnType("INTEGER")
                                .HasColumnName("height");

                            b1.Property<int>("Width")
                                .HasColumnType("INTEGER")
                                .HasColumnName("width");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "SceneId")
                        .IsUnique();

                    b.ToTable("motion_scene_codes", (string)null);
                });

            modelBuilder.Entity("MotionContext.Domain.Entities.SceneRevision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SceneCodeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SceneCodeId", "RevisionNumber")
                        .IsUnique();

                    b.ToTable("motion_scene_revisions", (string)null);
                });

            modelBuilder.Entity("MotionContext.Domain.Entities.SceneRevision", b =>
                {
                    b.HasOne("MotionContext.Domain.Entities.SceneCode", null)
                        .WithMany("Revisions")
                        .HasForeignKey("SceneCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MotionContext.Domain.Entities.SceneCode", b =>
                {
                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
